version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: "/example/"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "chore: "