include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - prefer_using_color_decision: true