name: flutter_dsfr
description: "Système de Design de l'État français en flutter"
version: 0.4.0
homepage: https://github.com/Octo-Open-Source/flutter-dsfr

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  intl: ^0.20.2

dev_dependencies:
  custom_lint: ^0.7.5
  dsfr_lints:
    git:
      url: https://github.com/Octo-Open-Source/flutter-dsfr-linter.git
      ref: 0.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icon_font_generator:
    git:
      url: https://github.com/Jupi007/icon_font_generator.git
      ref: yaru
  meta: ^1.16.0

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Marianne
      fonts:
        - asset: assets/fonts/Marianne-Light.otf
          weight: 300
        - asset: assets/fonts/Marianne-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Marianne-Regular.otf
          weight: 400
        - asset: assets/fonts/Marianne-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Marianne-Medium.otf
          weight: 500
        - asset: assets/fonts/Marianne-Bold.otf
          weight: 700
        - asset: assets/fonts/Marianne-BoldItalic.otf
          weight: 700
          style: italic
    - family: DsfrIcons
      fonts:
        - asset: assets/icons/Dsfr-Icons.otf
