name: Deploy web preview of DSFR

on:
  push:
    branches: ["feat/deploy-pages"]

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: 3.29.2

      - name: Install dependencies
        run: |
          cd example
          flutter pub get

      - name: Build for web
        run: |
          cd example/
          flutter build web --base-href "/flutter-dsfr/"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4