name: Static analysis of Dart and Flutter code

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: 3.32.1

      - name: Analyze project source
        run: flutter analyze

      - name: Run custom linters
        run: flutter pub run custom_lint

