name: Run tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: 3.32.1

      - name: Launch tests
        run: flutter test
